// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import "dotenv/config";
import { defineConfig, env } from "prisma/config";
import * as dotenv from 'dotenv';
import path from 'path';

// This forces Prisma to find your .env file relative to this config file

dotenv.config({ path: path.resolve(process.cwd(), '.env') });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // This MUST be the Direct URL for Neon migrations
    url: process.env.DIRECT_URL || "postgresql://neondb_owner:npg_rD6Ac3OZoEYB@ep-old-scene-aofxk3lj.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require",
  },
});

